services:
  webclient:
    container_name: dtt-center
    image: dtt-center/dtt-center:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
